jar 'org.kill-bill.billing:killbill-api', '0.9.9'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-notification', '0.7.4'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-payment', '0.7.4'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-currency', '0.7.4'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-retry', '0.7.4'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-invoice', '0.7.4'
jar 'org.kill-bill.billing:killbill-util:tests', '0.11.9'
jar 'javax.servlet:javax.servlet-api', '3.0.1'
