jar 'com.ning.billing:killbill-api', '0.3.3-SNAPSHOT'
jar 'com.ning.billing.plugin:killbill-plugin-api-notification', '0.3.1-SNAPSHOT'
jar 'com.ning.billing.plugin:killbill-plugin-api-payment', '0.3.1-SNAPSHOT'
jar 'com.ning.billing:killbill-util:tests', '0.3.6-SNAPSHOT'
jar 'javax.servlet:javax.servlet-api', '3.0.1'
