#!/usr/bin/env ruby
require 'rubygems'
require 'thor'

require File.expand_path('../../generators/killbill_generator', __FILE__)

Dir[File.expand_path('../..', __FILE__) + '/generators/*/*.rb'].each do |generator|
  require generator
end

class Generate < Thor
  register(ActiveMerchantGenerator, 'active_merchant', 'active_merchant NAME DIR', 'Generates a new active_merchant plugin for Kill Bill.')
end

Generate.start
